### ISSUE TITLE
[Error Handling Log] CSS로 자동 fadein/fadeout / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#162]
### CSS로 자동 fadein/fadeout

https://user-images.githubusercontent.com/83934037/134657288-376f1846-7a95-4ddd-bb73-3e57bc77b19c.mov

유저가 3D 전시관을 입장하게 되면  
화면 중앙 상단에 '전시관을 나가려면 esc키를 입력하세요' 메세지를 서서히 fadein으로 띄웠다가
일정 시간이 지나면 다시 서서히 fadeout 되게 하고 싶었다.

컴포넌트 내 코드는 아래와 같다. 
![image](https://user-images.githubusercontent.com/83934037/134653127-19d11efa-00a9-4077-89ec-a3d928c4a063.png)

```js
useEffect(()=> { //modal이 false가 되는 즉시 useEffect 내 함수가 호출된다!
    if(modal){

    } else{
    setContent(true);
    setTimeout(()=> {
      setContent(false);
    }, 2000)
    }
  }, [modal]);
```

위의 코드처럼 의도적인 `setTimeout` 함수를 사용하여 2초간의 term을 두었다. CSS 코드는 아래와 같다.
```css
.topContent {
  position: fixed;
  top: 1rem;
  left: 50%;
  transform: translate(-50%, 0);
  z-index: 10;
  width: 18rem;
  height: 7rem;
  display: flex;
  justify-content: center;
  align-items: center;
  color: rgb(94, 94, 94);
  background-color: white;
  border-radius: 10px;
  animation: fadein 2s;
  -moz-animation: fadein 2s;
  -webkit-animation: fadein 2s;
  -o-animation: fadein 2s;
}
.topContentClose {
  position: fixed;
  top: 1rem;
  left: 50%;
  transform: translate(-50%, 0);
  z-index: 10;
  width: 18rem;
  height: 7rem;
  display: flex;
  justify-content: center;
  align-items: center;
  color: rgb(94, 94, 94);
  background-color: white;
  border-radius: 10px;
  animation: fadeout 2s;
  -moz-animation: fadeout 2s;
  -webkit-animation: fadeout 2s;
  -o-animation: fadeout 2s;
  opacity: 0;
}

@-webkit-keyframes fadein {
  /* Safari and Chrome */
  from {
    opacity: 0;
  }

  to {
    opacity: 0.8;
  }
}
@-webkit-keyframes fadeout {
  /* Safari and Chrome */
  from {
    opacity: 0.8;
  }

  to {
    opacity: 0;
  }
}

```

문제는... `.topContentClose` 속성이 적용될 때 2초간 fadeout이 완료되고 갑자기 띡 다시 나타나는 것...!
css속성은 순서대로 읽히기 때문에... 마지막 속성값으로 `opacity: 0`을 주었더니 깔끔히 해결되었다.

### **에러 핸들링을 위해 참고한 레퍼런스 링크**
https://jess2.xyz/css/fade-in-out/
https://xe1.xpressengine.com/qna/15955640
