### ISSUE TITLE
[Dev Log] 20210917 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#66]
### **오늘의 결과물**

https://user-images.githubusercontent.com/83934037/133794398-6dc73e29-1aaa-4dec-9bd0-7a672aa7e8f3.mov

### **오늘 완료한 작업 목록**

<새롭게 완료한 것> 

1. Navbar 상단 고정 시도중(position sticky가 적용되질 않아서 [https://usagi-post.com/archives/1448](https://usagi-post.com/archives/1448) —> 해당 블로그 참고. 해결방법 찾는중)
2. 클라우드 배포 에러 사항 발견. 점검중.
3. 모바일 사이즈에서 발견한 레이아웃 깨짐(마이너한 사항) CSS 속성 수정.
4. Gallery 목록 & 상세페이지 내에서 보낼 api request 리스트업
5. three.js 학습중 --> https://youtu.be/fdtqqyeKRJk

<어제 못한 작업중 오늘 완료한 것>

1. (추가 작업 완료!!!) ~~이미지 카드 슬라이더 마우스 오버 시 좌/우 화살표 버튼 추가 제작하여 기능 개선 필요.~~
2. (극단적 예외 경우 제외하고, 어떠한 크기에도 반응하는 레이아웃으로 설정 완료)~~단일작품 확대 페이지 반응형 레이아웃을 살짝 변경 필요.(ref 사이트 참고)~~
```css
.img {
  position: absolute;
  width: 100%;
  max-width: 768px;
  height: auto;
  max-height: 90vh;
  object-fit: cover;
  /*...*/
}
```

### **오늘 작업 중 완료하지 못한 것들 목록(+에러)**

1. 이미지 카드 슬라이더 제작 완료. 다만 코드가 맘에 들지 않는다. 코드 리팩토링 필요.
2. (모바일 대응을 위한)이미지 카드 슬라이더 드래그로 좌/우 넘기기 *****(리액트 draggable 라이브러리 사용해야 할 지?)
3. 단일작품 확대 페이지에서 작품 설명 어떻게 overlay 시킬지 고민해봐야 함.
4. 작품 9개 나열할 때(3*3 grid) height 들쭉날쭉함. 여백 없이 나열해보는 방법 찾아보는 중... —> 이거 너무 찾기 어려움. grid 배열 방식이 아니라 flex column을 3줄 나열하는 방식일 수도 있음. 어차피 사진개수가 정해져 있으니 이 방법으로 레이아웃 바꿔도 될 것 같다.

### **내일 TO DO LIST**

1. react three fiber 학습
2. 랜딩페이지 레이아웃 & 컨텐츠 고민해보기
